language: rust
dist: trusty
rust:
  - stable
  - beta
  - nightly
env: LD_LIBRARY_PATH=/opt/python/3.6.0/lib/
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      # code coverage
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - zlib1g-dev
install:
  - git clone https://github.com/tobyn/zbase32.git pyzbase32
  - ( cd pyzbase32 && python3 ./setup.py install --user )
script:
  # not on nightly
  - '[[ "$TRAVIS_RUST_VERSION" = "nightly" ]] || cargo rustc --lib --verbose -- -D warnings'
  - '[[ "$TRAVIS_RUST_VERSION" = "nightly" ]] || cargo test --verbose --features python_tests'

  # nightly only
  - '[[ "$TRAVIS_RUST_VERSION" != "nightly" ]] || cargo rustc --lib --verbose --features clippy -- -D warnings'
  - '[[ "$TRAVIS_RUST_VERSION" != "nightly" ]] || cargo test --verbose --features unstable,python_tests'
after_success: |
  # code coverage
  if [[ "$TRAVIS_RUST_VERSION" = "stable" ]]; then
      wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
      tar xzf master.tar.gz &&
      cd kcov-master &&
      mkdir build &&
      cd build &&
      cmake .. &&
      make &&
      sudo make install &&
      cd ../.. &&
      rm -rf kcov-master &&
      for file in target/debug/*-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]; do
          mkdir -p "target/cov/$(basename $file)" || err=true
          kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file" || err=true;
      done &&
      [[ "${err-}" != "true" ]] &&
      bash <(curl -s https://codecov.io/bash) &&
      echo "Uploaded code coverage"
  fi
