[package]
name = "zbase32"
version = "0.0.1"
description = "Implementation of zbase32."
repository = "https://github.com/pgerber/zbase32-rust"
authors = ["Peter Gerber <peter@arbitrary.ch>"]
keywords = ["zbase32"]
license = "LGPL-3.0+"

[dependencies]
clippy = { version = "0.0", optional = true }
